version: '3'
services:
  dsdb:
    build:
      context: .
      dockerfile: Dockerfile-dsdb
    container_name: dsdb
    user: mysql
    networks:
      - ds-network
    volumes:
      - data-volume:/var/lib/mysql
  dsconnect:
    build:
      context: .
      dockerfile: Dockerfile-dsconnect
    container_name: dsconnect
    ports:
      - "54001:54001"
      - "54230:54230/tcp"
      - "54231:54231"
    networks:
      - ds-network
  dsgame:
    build:
      context: .
      dockerfile: Dockerfile-dsgame
    container_name: dsgame
    ports:
      - "54230:54230/udp"
    networks:
      - ds-network
  dssearch:
    build:
      context: .
      dockerfile: Dockerfile-dssearch
    container_name: dssearch
    ports:
      - "54002:54002"
    networks:
      - ds-network

networks:
  ds-network:
volumes:
  data-volume:
