version: '3'
services:
  dsdb:
    build:
      context: .
      dockerfile: Dockerfile-dsdb
    container_name: dsdb
    user: mysql
    networks:
      - ds-network
    volumes:
      - db-volume:/var/lib/mysql
  dsbuild:
    build:
      context: .
      dockerfile: Dockerfile-dsbuild
    container_name: dsbuild
    volumes:
      - build-volume:/usr/build
  dsconnect:
    build:
      context: .
      dockerfile: Dockerfile-dsconnect
    container_name: dsconnect
    depends_on:
      - dsdb
      - dsbuild
    ports:
      - "54001:54001"
      - "54230:54230/tcp"
      - "54231:54231"
    networks:
      - ds-network
    volumes:
      - build-volume:/usr/build
    stdin_open: true
    tty: true
  dsgame:
    build:
      context: .
      dockerfile: Dockerfile-dsgame
    container_name: dsgame
    depends_on:
      - dsdb
      - dsbuild
    ports:
      - "54230:54230/udp"
    networks:
      - ds-network
    volumes:
      - build-volume:/usr/build
  dssearch:
    build:
      context: .
      dockerfile: Dockerfile-dssearch
    container_name: dssearch
    depends_on:
      - dsdb
      - dsbuild
    ports:
      - "54002:54002"
    networks:
      - ds-network
    volumes:
      - build-volume:/usr/build

networks:
  ds-network:
volumes:
  db-volume:
  build-volume:
